### ISSUE TITLE
Change paymentHistory transfer object schema

### ISSUE THREAD

**Issue by melchanatan** [drived-dev/okmoney-backend#12]
paymentHistory should preferably be in this format
 
  id: string;
  loanId: string;
  debtorId: string;
  debtorFirstname: string;
  debtorLastname: string;
  amount: number;
  paymentDate?: number;
  paymentType: PaymentType;
  imageUrl?: string;
  createdAt?: number;
  updatedAt?: number;

**Comment by khajornritdacha** [comment]
Ok, can the frontend send the debtorFirstname and Lastname via the request so that backend does not have to query db again?
