### ISSUE TITLE
Loan status and loan id

### ISSUE THREAD

**Issue by melchanatan** [drived-dev/okmoney-backend#13]
# **Loan status**
it should be this

```
export enum LoanStatus {
  ค้างชำระ = 0,
  ใกล้กำหนด = 1,
  รอชำระ = 2,
  ครบชำระ = 3,
}
```

on loan.entity.ts

# **loan id**
can you run loanId with simpler code like 001 then 002 etc.

**Comment by khajornritdacha** [comment]
It is possible, but you need to create a Google Firebase function that is triggered on all create requests. Why do you want the loanId to be simpler?
