### ISSUE TITLE
Endpoint fails to return payment history when an internal error occurs.

### ISSUE THREAD

**Issue by melchanatan** [drived-dev/okmoney-backend#24]
**Steps to Reproduce**
1. Trigger `localhost:3000/api/payment/history`.
2. Ensure at least one of the entries causes an internal error (e.g., by deleting relating debtor or loan id).

**Expected Behavior**
The endpoint should handle internal errors gracefully by omitting problematic entries and returning the remaining payment history.

**Actual Behavior**
The endpoint fails entirely and does not return any data when an internal error occurs.

**Comment by khajornritdacha** [comment]
Fix in 26-th PR
